-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:217a063d0339886671cbc933f57473bf:2eb762ed023fea9c3a6bf59d52bc1a16:1800a70ed20e0202be67c8aaf813e2a9$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 2, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 24, y = 0, width = 40, height = 90 },
				textureRect = { x = 94, y = 2, width = 44, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 140, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 232, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 4, y = 0, width = 86, height = 90 },
				textureRect = { x = 324, y = 2, width = 86, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 412, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 504, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 596, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 688, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "9.png",
				spriteColorRect = { x = 0, y = 0, width = 90, height = 90 },
				textureRect = { x = 780, y = 2, width = 90, height = 90 },
				spriteSourceSize = { width = 90, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

